<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>The League</title>
        <link rel="stylesheet" href="assets/styles/css/style.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    </head>
    <body>
        <header>
            <h1>THE LEAGUE</h1>

            <div class="nav">
                <a href="">LES TEAMS</a>
                <a href="">LES PLAYERS</a>
                <a href="">LES MATCHS</a>
            </div>
        </header>
        
        <?php
            require "templates/partials/_title.phtml";
            require "templates/partials/_dailyTeam.phtml";
            require "templates/partials/_dailyPlayers.phtml";
        ?>
    </body>
</html>