<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>The League</title>
        <link rel="stylesheet" href="assets/styles/css/style.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="assets/styles/css/styleAmy.css" />
        <link rel="stylesheet" href="assets/styles/css/styleNathan.css" />
        
    </head>
    <body>
        <header>
            <h1><a href="index.php">THE LEAGUE</a></h1>

            <?php $gameManager = new GameManager() ;
                $mediaManager = new MediaManager() ;
                $playerManager = new PlayerManager() ;
                $player_perfManager = new Player_PerformanceManager() ;
                $teamManager = new TeamManager() ;
            ?>

            <div class="nav">
                <a href="index.php?route=teams">LES TEAMS</a>
                <a href="index.php?route=players">LES PLAYERS</a>
                <a href="index.php?route=matchs">LES MATCHS</a>
            </div>
        </header>
        
        <?php
            require $template;
        ?>
    </body>
</html>