<section>

    <h3>LA TEAM À LA UNE</h3>

    <div>
        <img src="assets/images/placeholder.png" alt="$team->getLogo()->getAlt()">

        <div>

            <h4>placeholder</h4>
            
            <p>Les players</p>
            
            <!-- ?php foreach ($team->get as ){ ?> -->
                <div>
                    
                    <img src="assets/images/placeholder.png" alt="Photo de profil de ...">
                    
                    <p>placeholder</p>
                    
                </div>
            <!-- ?php } ?> -->
        </div>
    </div>

</section>