<div>

    <h2>LES PLAYERS DE LA LEAGUE</h2>

    <div>

        <?php $players = $playerManager->findAll();
        foreach ($players as $player){
            $playerName = $player->getNickname();
            $imageInfo = $player->getPortrait();?>
        <div>
            <img src="<?= $imageInfo->getUrl() ?>" alt="<?= $imageInfo->getAlt() ?>">
            <h3><?= $playerName ?></h3>
            <h4><?= $player->getTeam()->getName() ?></h4>
            <a href="index.php?route=match&id=<?= $player->getId() ?>">Découvrez <?= $playerName ?></a>
        </div>
        <?php } ?>

    </div>

</div>