<section>

    <h2>LES PERFORMANCES</h2>

    <div>
    <?php $perfs = $player_perfManager->findPerf($data["id"]); ?>

    <?php foreach ($perfs as $perf) { ?>

        <div>

            <p><?=$perf->getPlayer()->getNickname() ?></p>
            <p><?=$perf->getTeam()->getName() ?></p>
            <p><?=$perf->getPoints() ?></p>
            <p><?=$perf->getAssists() ?></p>

        </div>

    <?php } ?>
    
    </div>

</section>