<section class="">
    <h2>Les Matchs</h2>

    <div class="">
        <h3>PATHERS VS SPARROW</h3>
        <p>17/01/2024</p>
        <img src="assets/images/placeholder.png" alt="placeholder" class="image gagnante">
        <img src="assets/images/placeholder.png" alt="placeholder" class="image perdante">
        <div class="detail_match">
            <p>DÉTAIL DU MATCH</p>
        </div>
    </div>
</section>