<section class="LES_MATCHS">
    <h2>LES MATCHS</h2>
    <div class="matchs">
        <h3>VENDETTA VS OWLS</h3>
        <p>17/01/2024</p>
        <img src="assets/images/placeholder.png" alt="placeholder" class="image gagnante">
        <img src="assets/images/placeholder.png" alt="placeholder" class="image perdante">
    <div class="detail_match">
        <p>DÉTAIL DU MATCH</p>
    </div>
</div>
</section>