<div>

    <h4>SA TEAM</h4>

    <div>

        <?php $players = $playerManager->findAll();
        foreach ($players as $teamMate){
            if ($player->getTeam()->getId() === $teamMate->getTeam()->getId() && $player->getId() !== $teamMate->getId()){
                $playerName = $teamMate->getNickname();
                $imageInfo = $teamMate->getPortrait();?>

                <div>
                    <img src="<?= $imageInfo->getUrl() ?>" alt="<?= $imageInfo->getAlt() ?>">
                    <h3><?= $playerName ?></h3>
                    <a href="index.php?route=player&id=<?= $teamMate->getId() ?>">Découvrez <?= $playerName ?></a>
                </div>
            <?php } ?>
        <?php } ?>

    </div>

</div>