<section class="flex_column" id="">

    <h3>LA TEAM À LA UNE</h3>

    <?php $team = $teamManager->findOne(1); ?>
    <?php $players = $playerManager->findAll(); ?>

    <div class="border">
        <img class="dailyTeamLogo" src=<?= $team->getLogo()->getUrl()?> alt="<?= $team->getLogo()->getAlt()?>">

        <div class="joueurs">

            <h4><?= $team->getName()?></h4>
            
            <p>Les players</p>
            
            <?php foreach ($players as $player) { ?>
                <?php if ($player->getTeam()->getId() === $team->getId()) { ?>

                    <div>
                        
                        <img src="<?= $player->getPortrait()->getUrl()?>" alt="<?= $player->getPortrait()->getAlt()?>">
                        
                        <p><?= $player->getNickname()?></p>
                        
                    </div>

                <?php } ?>
            <?php } ?>

        </div>
    </div>

</section>