<section>

    <h3>LE DERNIER MATCH</h3>

   <div>

   <?php $game = $gameManager->findOne(3); ?>

        <h4><?= $game->getName()?></h4>

        <p><?= $game->getDate()->format('Y-m-d H:i:s')?></p>

        <div>
            <div>
                <img src=<?= $game->getTeam1()->getLogo()->getUrl()?> alt="<?= $game->getTeam1()->getLogo()->getAlt()?>">
            </div>
            
            <div>
                <img src=<?= $game->getTeam2()->getLogo()->getUrl()?> alt="<?= $game->getTeam2()->getLogo()->getAlt()?>">
            </div>
        </div>

   </div>

</section>